PersonalCollectionManagement/Models/Collection.cs
using Microsoft.AspNetCore.Html;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace PersonalCollectionManagement.Models
{
    public class Collection
    {
        public Collection(string name, string description, string image)
        {
            Name = name;
            Description = description;
            Image = image;
        }

        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }

        public string Name { get; set; }

        public string Description { get; set; }

        public string Image { get; set; }

        [ForeignKey("User")]
        public string UserId { get; set; }

        [NotMapped]
        public HtmlString MarkdownDescription
        {
            get
            {
                return Markdown.ParseHtmlString(Description);
            }
        }

        [NotMapped]
        public int CountItems { get; set; }

        [NotMapped]
        public List<Field> Fields{ get; set; }

        [NotMapped]
        public User OwnerCollection { get; set; }

        [NotMapped]
        public string FormattedFields { 
            get 
            {
                string result = "";
                for (int i = 0; i < Fields.Count; i++)
                {
                    result += Fields[i].Name + "," + Fields[i].Type;

                    if(i != Fields.Count - 1)
                    {
                        result += ";";
                    }
                }
                return result;
            }  
        }
    }
}

PersonalCollectionManagement/Models/Item.cs
using Microsoft.AspNetCore.Html;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace PersonalCollectionManagement.Models
{
    public class Item
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }
        public string Name { get; set; }

        [ForeignKey("Collection")]
        public int CollectionId { get; set; }

        [NotMapped]
        public List<HtmlString> MarkdownFormattedValues
        {
            get
            {
                List<HtmlString> markdownValues = new List<HtmlString>();
                for (int i = 0; i < Values.Count; i++)
                {
                    markdownValues.Add(Markdown.ParseHtmlString(Values[i]));
                }
                return markdownValues;
            }
        }

        [NotMapped]
        public List<string> Values { get; set; }

        [NotMapped]
        public List<string> Tags { get; set; }

        [NotMapped]
        public Collection Collection { get; set; }
    }
}

PersonalCollectionManagement/Models/User.cs
using Microsoft.AspNetCore.Identity;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace PersonalCollectionManagement.Models
{
    public class User : IdentityUser
    {
        public User(string nickname, string email)
        {
            Nickname = nickname;
            Email = email;
            this.IsAdmin = false;
            this.Status = "Разблокирован";
        }

        public bool IsAdmin { get; set; }
        public string Nickname { get; set; }

        public string Status { get; set; }

        public DateTime DateRegistration { get; set; }

        public DateTime DateLastLogin { get; set; }
    }
}

PersonalCollectionManagement/Controllers/CollectionController.cs
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using PersonalCollectionManagement.Models;
using PersonalCollectionManagement.ViewModels;
using PersonalCollectionManagement.Services;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using PersonalCollectionManagement.Services.CollectionServices;

namespace PersonalCollectionManagement.Controllers
{
    public class CollectionController : Controller
    {
        public CollectionController(ApplicationContext applicationContext)
        {
            Database.SetDB(applicationContext);
        }

        [HttpPost]
        public async Task<IActionResult> CreateCollection(CollectionModel collectionModel)
        {
            await CollectionAdder.AddCollection(collectionModel);
            return RedirectToAction("UserPage", "Home", new { idUser = collectionModel.IdUser});
        }

        [HttpPost]
        public async Task<IActionResult> DeleteCollection(int idCollection)
        {
            User ownerUser = UsersSearcher.GetUser(idCollection);
            await CollectionDeleter.DeleteCollectionAsync(idCollection);
            return RedirectToAction("UserPage", "Home", new { idUser = ownerUser.Id });
        }


        [HttpPost]
        public async Task<IActionResult> EditCollection(CollectionModel collectionModel)
        {
            await CollectionUpdater.UpdateCollection(collectionModel);
            return RedirectToAction("UserPage", "Home", new { idUser = collectionModel.IdUser });
        }
    }
}

PersonalCollectionManagement/Controllers/HomeController.cs
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using PersonalCollectionManagement.Models;
using PersonalCollectionManagement.Services;
using PersonalCollectionManagement.Services.CommentServices;
using PersonalCollectionManagement.Services.LikeServices;

namespace PersonalCollectionManagement.Controllers
{
    public class HomeController : Controller
    {
        public HomeController(ApplicationContext applicationContext, IWebHostEnvironment appEnvironment)
        {
            Database.SetDB(applicationContext);
            AppInviroment.SetAppEnvironment(appEnvironment);
        }

        public async Task<IActionResult> Index()
        {
            await SetViewBag();

            ViewBag.LastAddedItems = ItemSearcher.GetLastAddedItems(5);

            ViewBag.CollectionsWithMostOfItems = CollectionSearcher.GetCollectionsWithMostOfItems(5);

            ViewBag.AllTegs = TagsSearcher.GetTagsValues();

            return View();
        }

        public async Task<IActionResult> UserPage(string idUser)
        {
            await SetViewBag();

            ViewBag.OwnerCollections = UsersSearcher.GetUser(idUser);

            return View(CollectionSearcher.GetUserCollections(idUser));
        }

        public async Task<IActionResult> Collections()
        {
            await SetViewBag();
            return View(Database.db.Collections.ToList());
        }

        public async Task<IActionResult> Collection(int idCollection)
        {
            await SetViewBag();

            ViewBag.Collection = CollectionSearcher.GetCollection(idCollection);

            return View(ItemSearcher.GetCollectionItems(idCollection));
        }

        public async Task<IActionResult> Users()
        {
            await SetViewBag();
            return View(Database.db.Users.ToList());
        }
        public async Task<IActionResult> Item(int id)
        {
            await SetViewBag();

            User autorizeUser = await GetAutorizeUser();
            Item item = ItemSearcher.GetItem(id);
            ViewBag.Collection = CollectionSearcher.GetCollection(item.CollectionId);
            ViewBag.Comments = CommentSearcher.GetItemComments(item.Id);

            List<Like> likes = LikeSearcher.GetItemLikes(item.Id);
            ViewBag.CountLikes = likes.Count;
            ViewBag.IsUserLike = LikeSearcher.IsUserLike(autorizeUser, likes);

            return View(item);
        }

        public async Task<IActionResult> UserSettings()
        {
            ViewBag.Language = CultureHandler.GetCulture();
            await SetViewBag();
            return View();
        }

        [NonAction]
        public async Task<User> GetAutorizeUser()
        {
            return await Database.db.Users.FirstOrDefaultAsync(u => u.Email == User.Identity.Name);
        }

        [NonAction]
        public async Task<bool> SetViewBag()
        {
            ViewBag.AutorizeUser = await GetAutorizeUser();
            ViewBag.Bg = HttpContext.Request.Cookies["Theme"] == null ? "dark" : HttpContext.Request.Cookies["Theme"];
            ViewBag.Text = ViewBag.Bg == "dark" ? "light" : "dark";
            return true;
        }
    }
}

PersonalCollectionManagement/Controllers/ItemController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using PersonalCollectionManagement.Models;
using PersonalCollectionManagement.Services;
using PersonalCollectionManagement.Services.ItemServices;
using PersonalCollectionManagement.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PersonalCollectionManagement.Controllers
{
    public class ItemController : Controller
    {

        public ItemController(ApplicationContext applicationContext)
        {
            Database.SetDB(applicationContext);
        }

        #region Item
        [HttpPost]
        public async Task<IActionResult> CreateItem(ItemModel itemModel)
        {
            await ItemAdder.AddItemAsync(itemModel);

            return RedirectToAction("Collection", "Home", new { idCollection = itemModel.IdCollection});
        }

        public async Task<IActionResult> DeleteItem(int idItem)
        {
            Item item = ItemSearcher.GetItem(idItem);
            int collectionId = item.CollectionId;
            await ItemDeleter.DeleteItemAsync(idItem);
            return RedirectToAction("Collection", "Home", new { idCollection = collectionId});
        }

        [HttpPost]
        public async Task<IActionResult> EditItem(ItemModel itemModel)
        {
            await ItemUpdater.UpdateItemAsync(itemModel);

            return RedirectToAction("Collection", "Home", new { idCollection = itemModel.IdCollection });
        }

        #endregion
    }
}

PersonalCollectionManagement/Controllers/SearchController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using PersonalCollectionManagement.Models;
using PersonalCollectionManagement.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PersonalCollectionManagement.Controllers
{
    public class SearchController : Controller
    {
        public SearchController(ApplicationContext applicationContext)
        {
            Database.SetDB(applicationContext);
        }

        public async Task<IActionResult> Items(string act, string searchValue)
        {
            await SetViewBag();
            List<Item> items = ItemSearcher.GetAllItems();

            if (act == "search")
            {
                return View(Search(searchValue));
            }
            else
            {
                List<Tag> searchedTags = TagsSearcher.GetTags(searchValue);

                return View(ItemSearcher.GetItemsByTags(searchedTags));
            }
        }

        [NonAction]
        private List<Item> Search(string searchValue)
        {
            List<Item> items = Database.db.Items.ToList();
            List<Tag> tags = Database.db.Tags.ToList();
            List<Value> values = Database.db.Values.ToList();
            searchValue = "%" + searchValue + "%";

            Task<List<int>>[] tasks = new Task<List<int>>[4]
            {
                new Task<List<int>>(() =>
                {
                return items.Where(x => EF.Functions.Like(x.Name, searchValue)).Select(item => item.Id).ToList();
                }),
                new Task<List<int>>(() =>
                {
                return tags.Where(x => EF.Functions.Like(x.Value, searchValue)).Select(tag => tag.IdItem).ToList();
                }),
                new Task<List<int>>(() =>
                {
                    return values.Where(x => EF.Functions.Like(x.Information, searchValue)).Select(value => value.IdItem).ToList();
                }),

                new Task<List<int>>(() =>
                {
                    return Database.db.Comments.Where(x => EF.Functions.Like(x.Text, searchValue)).Select(comment => comment.ItemId).ToList();
                })
            };

            foreach (var t in tasks)
            {
                t.Start();
            }

            Task.WaitAll(tasks);

            List<int> allSearchedItemsId = tasks[0].Result.
                 Union(tasks[1].Result.
                 Union(tasks[2].Result.
                 Union(tasks[3].Result))).ToList();

            return items.Where(item => allSearchedItemsId.Contains(item.Id)).ToList();
        }

        [NonAction]
        public async Task<User> GetAutorizeUser()
        {
            return await Database.db.Users.FirstOrDefaultAsync(u => u.Email == User.Identity.Name);
        }

        [NonAction]
        public async Task<bool> SetViewBag()
        {
            ViewBag.AutorizeUser = await GetAutorizeUser();
            ViewBag.Bg = HttpContext.Request.Cookies["Theme"];
            ViewBag.Text = ViewBag.Bg == "Dark" ? "Light" : "Dark";
            return true;
        }
    }
}

PersonalCollectionManagement/Controllers/UsersController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Localization;
using PersonalCollectionManagement.Models;
using PersonalCollectionManagement.Services;
using PersonalCollectionManagement.Services.UserServices;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PersonalCollectionManagement.Controllers
{
    public class UsersController : Controller
    {
        private readonly IStringLocalizer<UsersController> localizer;

        public UsersController(ApplicationContext applicationContext, IStringLocalizer<UsersController> localizer)
        {
            Database.SetDB(applicationContext);
            this.localizer = localizer;
        }

        public async Task<IActionResult> ChangeStatus(string idUser)
        {
            User user = UsersSearcher.GetUser(idUser);

            user.Status = user.Status == "Разблокирован" ? localizer["Blocked"] : localizer["Unlocked"];
            await UsersUpdater.UpdateUserAsync(user);
            return RedirectToAction("Users", "Home");
        }

        public async Task<IActionResult> Delete(string idUser)
        {
            await UsersDeleter.DeleteUserAsync(idUser);
            return RedirectToAction("Users", "Home");
        }

        public async Task<IActionResult> AppointAdministrator(string idUser)
        {
            User user = UsersSearcher.GetUser(idUser);
            user.IsAdmin = true;
            await UsersUpdater.UpdateUserAsync(user);
            return RedirectToAction("Users", "Home");
        }
    }
}

PersonalCollectionManagement/Views/Home/Collections.cshtml
@using Microsoft.AspNetCore.Mvc.Localization
@inject IViewLocalizer Localizer
@{
    @model List<PersonalCollectionManagement.Models.Collection>
    ViewData["CurrentPage"] = "Collections";
    ViewData["Title"] = Localizer["Collections"];
}

@if (Model.Count == 0)
{
    <h2 class="text-info m-2">@Localizer["CollectionListIsEmpty"]</h2>
}
else
{
    <h2 class="text-info m-2">@Localizer["CollectionList"]</h2>
    <table class="table table-responsive-sm table-bordered table-hover table-@ViewBag.Bg">
        <thead>
            <tr>
                <th scope="col">@Localizer["NameCollection"]</th>
                <th scope="col">@Localizer["DescriptionCollection"]</th>
                <th scope="col">@Localizer["GoTo"]</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var collection in Model)
            {
                <tr>
                    <th scope="row">@collection.Name</th>
                    <td>@collection.MarkdownDescription</td>

                    <td>
                        <form asp-controller="Home" asp-action="Collection" asp-route-idCollection="@collection.Id">
                            <button class="btn btn-primary" collectionId="@collection.Id">@Localizer["GoTo"]</button>
                        </form>
                    </td>
                </tr>
            }
        </tbody>
    </table>
}

PersonalCollectionManagement/Views/Home/Index.cshtml
@using Microsoft.AspNetCore.Mvc.Localization
@inject IViewLocalizer Localizer
@{
    ViewData["Title"] = Localizer["Title"];
    ViewData["CurrentPage"] = "Main";
}

<h5 class="text-info ml-2">@Localizer["LastAddedItems"]</h5>

<table class="table table-responsive-sm table-bordered table-hover table-@ViewBag.Bg">
    <thead>
        <tr>
            <th scope="col">@Localizer["NameElement"]</th>
            <th scope="col">@Localizer["Tegs"]</th>
            <th scope="col">@Localizer["GoToElementCollection"]</th>
            <th scope="col">@Localizer["GoToElementOwner"]</th>
            <th scope="col">@Localizer["GoToElement"]</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in ViewBag.LastAddedItems)
        {
            <tr>
                <th scope="row">@item.Name</th>
                <td>
                    @foreach (var tag in item.Tags)
                    {
                        <a>#@tag</a>
                    }
                </td>
                <td>
                    <form asp-controller="Home" asp-action="Collection" asp-route-idCollection="@item.CollectionId">
                        <button class="btn btn-primary">
                            @Localizer["GoToElementCollection"]
                        </button>
                    </form>
                </td>

                <td>
                    <form asp-controller="Home" asp-action="UserPage" asp-route-idUser="@item.Collection.UserId">
                        <button class="btn btn-primary">
                            @Localizer["GoToElementOwner"]
                        </button>
                    </form>
                </td>

                <td>
                    <form asp-controller="Home" asp-action="Item" asp-route-id="@item.Id">
                        <button class="btn btn-primary">
                            @Localizer["GoToElement"]
                        </button>
                    </form>
                </td>
            </tr>
        }
    </tbody>
</table>

<h5 class="text-info ml-2">@Localizer["CollectionsWithMostOfItems"]</h5>

<table class="table table-responsive-sm table-bordered table-hover table-@ViewBag.Bg">
    <thead>
        <tr>
            <th scope="col">@Localizer["NameCollection"]</th>
            <th scope="col">@Localizer["DescriptionCollection"]</th>
            <th scope="col">@Localizer["CountElements"]</th>
            <th scope="col">@Localizer["GoToOwnerCollection"]</th>
            <th scope="col">@Localizer["GoToCollection"]</th>
        </tr>
    </thead>
    <tbody>
        @foreach (Collection collection in ViewBag.CollectionsWithMostOfItems)
        {
            <tr>
                <th scope="row">@collection.Name</th>
                <td>@collection.MarkdownDescription</td>
                <td>@collection.CountItems</td>

                <td>
                    <form asp-controller="Home" asp-action="UserPage" asp-route-idUser="@collection.UserId">
                        <button class="btn btn-primary">
                            @Localizer["GoToOwnerCollection"]
                        </button>
                    </form>
                </td>

                <td>
                    <form asp-controller="Home" asp-action="Collection" asp-route-idCollection="@collection.Id">
                        <button class="btn btn-primary">
                            @Localizer["GoToCollection"]
                        </button>
                    </form>
                </td>
            </tr>
        }
    </tbody>
</table>

<div class="m-2">
    @foreach (var tag in ViewBag.AllTegs)
    {
        <a class="text-@ViewBag.Text" asp-controller="Search" asp-action="Items" asp-route-searchValue="@tag">#@tag </a>
    }
</div>

PersonalCollectionManagement/Views/Home/Item.cshtml
@using Microsoft.AspNetCore.Mvc.Localization
@inject IViewLocalizer Localizer
@{
    @model PersonalCollectionManagement.Models.Item

    ViewData["Title"] = Localizer["Element"].Value + " " + Model.Name;
}

<p class="d-none" id="isUserLike">@ViewBag.IsUserLike</p>
<p class="d-none" id="idItem">@Model.Id</p>
<table class="table table-responsive-sm table-bordered table-hover table-@ViewBag.Bg">
    <thead>
        <tr>
            <th scope="col">@Localizer["ItemName"]</th>
            @foreach (var field in ViewBag.Collection.Fields)
            {
                <th scope="col">@field.Name</th>
            }

            <th scope="col">@Localizer["Likes"]</th>
            <th scope="col">@Localizer["Comments"]</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <th scope="row">@Model.Name</th>

            @for (var i = 0; i <  ViewBag.Collection.Fields.Count; i++)
            {
                var field =  ViewBag.Collection.Fields[i];

                @if (field.Type == "Текстовый")
                {
                    <th scope="row">@Model.MarkdownFormattedValues[i]</th>
                }

                @if (field.Type == "Логический")
                {
                    @if (Model.Values[i] == "on")
                    {
                        <th scope="row"><input type="checkbox" disabled checked></th>
                    }
                    else
                    {
                        <th scope="row"><input type="checkbox" disabled></th>
                    }
                }

                @if (field.Type != "Текстовый" && field.Type != "Логический")
                {
                    <th scope="row">@Model.Values[i]</th>
                }
            }

            <th scope="row">
                @if (ViewBag.IsUserLike)
                {
                    <img class="mr-2 like likeAndComment" src="~/img/LikePressed.png">
                }
                else
                {
                    <img class="mr-2 like likeAndComment" src="~/img/Like.png">
                }
                <span id="countLikes">@ViewBag.CountLikes</span>
            </th>

            <th scope="row">
                <img class="mr-2 likeAndComment" src="~/img/Comment.png">
                <span id="countComments">@ViewBag.Comments.Count</span>
            </th>
        </tr>
    </tbody>
</table>

<div class="modal-dialog" role="document" id="formCommentModal">
    <div class="modal-content text-@ViewBag.Text bg-@ViewBag.Bg">
        <div class="modal-header ">
            <h5 class="modal-title">@Localizer["LeaveYourComment"]</h5>
        </div>
        <form name="commentForm">
            <div class="modal-body">
                <div class="container-fluid">
                    <textarea name="text" rows="4" cols="30"></textarea>
                </div>
            </div>
            <div class="modal-footer">
                <button class="btn btn-primary">@Localizer["Comment"]</button>
            </div>
        </form>
    </div>
</div>

@foreach (var comment in ViewBag.Comments)
{
    <div>
        <div class="modal-dialog" role="document">
            <div class="modal-content text-@ViewBag.Text bg-@ViewBag.Bg">
                <div class="modal-header ">
                    <h5 class="modal-title ">@comment.User.Nickname</h5>
                    <p>@comment.DateTime</p>
                </div>
                <div class="modal-body">
                    <div class="container-fluid">
                        <span>@comment.Text</span>
                    </div>
                </div>
            </div>
        </div>
    </div>
}

<div class='modal fade' id='notFullAccess' tabindex="-1" role="dialog"
     aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered " role="document">
        <div class="modal-content @ViewBag.Text bg-@ViewBag.Bg">
            <div class="modal-header ">
                <h5 class="modal-title text-danger">@Localizer["YouAreNotAuthorized"]</h5>
                <button class="close autorization" type="button" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <p class="text-info">@Localizer["WarningToUnauthorizedUser"]</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Ок</button>
                <form asp-controller="Account" asp-action="Login" method="get">
                    <input name="idCollection" id="idCollection" class="d-none">
                    <button type="submit" class="btn btn-primary">@Localizer["GoToAuthorization"]</button>
                </form>
            </div>
        </div>
    </div>
</div>


<script src="~/js/signalr/dist/browser/signalr.min.js"></script>
<script src="~/js/Item.js"></script>

PersonalCollectionManagement/Views/Home/Items.cshtml
@using Microsoft.AspNetCore.Mvc.Localization
@inject IViewLocalizer Localizer
@{
    @model List<PersonalCollectionManagement.Models.Item>
    ViewData["Title"] = Localizer["Items"];
}

@if (Model.Count == 0)
{
    <p class="text-info">@Localizer["NoResults"]</p>
}
else
{
    <table class="table table-responsive-sm table-bordered table-hover table-@ViewBag.Bg">
        <thead>
            <tr>
                <th scope="col">@Localizer["ItemName"]</th>
                <th scope="col">@Localizer["Tegs"]Теги</th>
                <th scope="col">@Localizer["GoToItemCollection"]</th>
                <th scope="col">@Localizer["GoToItemOwner"]</th>
                <th scope="col">@Localizer["GoToItem"]</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <th scope="row">@item.Name</th>
                    <td>@item.Tegs</td>

                    <td>
                        <form asp-controller="Home" asp-action="Collection" asp-route-idCollection="@item.CollectionId">
                            <button class="btn btn-primary">
                                @Localizer["GoToItemCollection"]
                            </button>
                        </form>
                    </td>

                    <td>
                        <form asp-controller="Home" asp-action="UserPage" asp-route-idUser="@item.Collection.UserId">
                            <button class="btn btn-primary">
                                @Localizer["GoToItemOwner"]
                            </button>
                        </form>
                    </td>

                    <td>
                        <form asp-controller="Home" asp-action="Item" asp-route-id="@item.Id">
                            <button class="btn btn-primary">
                                @Localizer["GoToItem"]
                            </button>
                        </form>
                    </td>
                </tr>
            }
        </tbody>
    </table>
}

PersonalCollectionManagement/Views/Home/UserSettings.cshtml
@using Microsoft.AspNetCore.Mvc.Localization
@inject IViewLocalizer Localizer
@{
    ViewData["Title"] = Localizer["Settings"];
}

<div class="m-3">
    <h2 class="text-@ViewBag.Text">@Localizer["ProfileSettings"]</h2>

    <form asp-controller="Settings" asp-action="ChangeLanguage">
        <p class="text-@ViewBag.Text">@Localizer["ChooseLanguage"]</p>
        <select class="text-@ViewBag.Text bg-@ViewBag.Bg languageSelect">
            @if (ViewBag.Language == "ru")
            {
                <option selected>@Localizer["Russian"]</option>
                <option>@Localizer["English"]</option>
            }
            else
            {
                <option>@Localizer["Russian"]</option>
                <option selected>@Localizer["English"]</option>
            }
        </select>

        <input class="d-none"
               name="language"
               id="languageValue"
               value="@ViewBag.Language">

        <button type="submit" class="btn btn-primary">@Localizer["SaveChanges"]</button>
    </form>

    <form asp-controller="Settings" asp-action="ChangeTheme">
        <p class="text-@ViewBag.Text">@Localizer["ChooseATopic"]</p>
        <select class="text-@ViewBag.Text bg-@ViewBag.Bg themeSelect">
            @if (ViewBag.Bg == "dark")
            {
            <option selected>@Localizer["Dark"]</option>
            <option>@Localizer["Light"]</option>
            }
            else
            {
                <option>@Localizer["Dark"]</option>
                <option selected>@Localizer["Light"]</option>
            }

        </select>
        <input class="d-none"
               name="theme"
               value="@ViewBag.Bg"
               id="ThemeValue">
        <button type="submit" class="btn btn-primary">@Localizer["SaveChanges"]</button>
    </form>
</div>

<script src="~/js/settings.js"></script>